### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by Yochran** [icynnac/bruhcmd#2]
**Line 26:**

`@SuppressWarnings("unused")`

This is not needed

**Line 30-40:**
```java
if (Bukkit.getVersion().contains("1.12.2")) {
            BukkitScheduler scheduler = getServer().getScheduler();
            scheduler.scheduleSyncDelayedTask(this, new Runnable() {
                @Override
                public void run() {
                    Bukkit.getConsoleSender().sendMessage(ChatColor.AQUA + "BruhCMD >> " + ChatColor.RED + "You're running an older version of spigot, some things in BruhCMD");
                    Bukkit.getConsoleSender().sendMessage(ChatColor.AQUA + "BruhCMD >> " + ChatColor.RED + "may be changed/broken. Submit any bug reports to my GitHub issues page:");
                    Bukkit.getConsoleSender().sendMessage(ChatColor.AQUA + "BruhCMD >> " + ChatColor.AQUA + "https://github.com/icynnac/bruhcmd/issues");
                }
            }, 20*10);
        }
```
        
None of this is needed, this plugin will run on any version of the game, just use XMaterial for the leather items further down in /sus command.

**Line 46-52:**
```java
new UpdateChecker(this, 85804).getVersion(version -> {
            if (this.getDescription().getVersion().equalsIgnoreCase(version)) {
                Bukkit.getConsoleSender().sendMessage(ChatColor.AQUA + "BruhCMD >> " + ChatColor.RED + "No updates available.");
            } else {
                Bukkit.getConsoleSender().sendMessage(ChatColor.AQUA + "BruhCMD >> " + ChatColor.GREEN + "Theres an update available! Head to the BruhCMD Spigot page to update.");
            }
        });
```

You can just change the if statement to check if it has an update available by adding an '!' before this.getDescription() in the first line of the if statement. This way you don't need to say "No Updates Available", it will only print out something if there is an update available.

**Line 55-57:**
```java
@Override
    public void onDisable(){
    }
```

This can be removed entirely since you're not putting anything in it.

**Line 59 (Command):**

don't put your commands in your main class. Make a separate class for it.

**Runnables (Multiple separate lines):**

Change the way you do runnables. Make them look something like this for simplicity, and no possible class errors.

```java
new BukkitRunnable() {
  @override
  public void run() {
    // code
  }
}.runTaskLater(instance-of-plugin, delay);
```

As well as this, when putting in your delay, you don't need to do 20*5. This just makes the server do more calculations, which you want to leave minimal when running a bigger plugin in the future, Just write 100.

**Line 120-123:**
```java
                   Player p = (Player) sender;
                    Location loc = p.getLocation();
                    Vector center = loc.toVector();
                    Vector toThrow = p.getLocation().toVector();
```

You defined the "loc" variable as the player's location. Then you defined the "center" variable as the vector to the loc variable (the player's location). Then you define "toThrow" which is once again the vector to the player's location. Just because you're defining one as "p.getLocation().toVector()" doesnt mean that "loc.toVector();" will be different when the "loc" variable is "p.getLocation();"

**Line 128:**
```java
Vector v = new Vector (x, 1, z).normalize ().multiply (3.5);
```

Remove random spaces.

**Everything below line 135:**

As I said before with the leather armor, use XMaterial so that the plugin will work on every version without complications. I personally use this in my plugins, its a very useful utility to have.

When setting armor, you shouldn't use p.getEquipment();, instead you should use p.getInventory();. Both have the setHelmet, setChestplate, setBoots and setLeggings methods in them.

Same thing i said above with the runnables, simplify them and remove calculations.

You put "return false;" at the end of your command. Put this command into a separate class and change "return false" to "return true".

**All of these things should help your coding time, efficiency, size, and speed, as well as fixing up any potential errors that could occur in the plugin.**

**Also, I strongly recommend making a Utils class where you can make a method to automatically translate color codes, a method so you can send messages with & symbols for color codes, etc.**

**Comment by icynnac** [comment]
thanks for the advice! i'll definately remove the ondisable lol, and ill see what i can do about doing most of this!
